// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFQIi3pNiQNoM4y7dBKxBCp-lzeqSPfg8',
    appId: '1:702148614087:web:7615cf62cdbb20e7c52be2',
    messagingSenderId: '702148614087',
    projectId: 'flutter-chat-aliyazdi',
    authDomain: 'flutter-chat-aliyazdi.firebaseapp.com',
    storageBucket: 'flutter-chat-aliyazdi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPUupMZG6HPmM4PtOK4gXwmx8d8w59A1U',
    appId: '1:702148614087:android:0b2f8b54f630d9a3c52be2',
    messagingSenderId: '702148614087',
    projectId: 'flutter-chat-aliyazdi',
    storageBucket: 'flutter-chat-aliyazdi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo0OsuWh-UAuo5bIaCkTcAyKKMXv3WCFA',
    appId: '1:702148614087:ios:73472d1002f63b85c52be2',
    messagingSenderId: '702148614087',
    projectId: 'flutter-chat-aliyazdi',
    storageBucket: 'flutter-chat-aliyazdi.appspot.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo0OsuWh-UAuo5bIaCkTcAyKKMXv3WCFA',
    appId: '1:702148614087:ios:ddc5b5ab5be1ea1dc52be2',
    messagingSenderId: '702148614087',
    projectId: 'flutter-chat-aliyazdi',
    storageBucket: 'flutter-chat-aliyazdi.appspot.com',
    iosBundleId: 'com.example.flutterChat.RunnerTests',
  );
}
